set QMAKE_SPEC=win32-msvc2013
set QMAKE_VERSION=3.0
set QMAKE_XSPEC=win32-msvc2013
set QT_HOST_BINS=D:\Qt\Qt5.2RC1\bin
set QT_HOST_DATA=D:\Qt\Qt5.2RC1
set QT_HOST_LIBS=D:\Qt\Qt5.2RC1\lib
set QT_HOST_PREFIX=D:\Qt\Qt5.2RC1
set QT_INSTALL_ARCHDATA=D:\Qt\Qt5.2RC1
set QT_INSTALL_BINS=D:\Qt\Qt5.2RC1\bin
set QT_INSTALL_CONFIGURATION=
set QT_INSTALL_DATA=D:\Qt\Qt5.2RC1
set QT_INSTALL_DEMOS=D:\Qt\Qt5.2RC1\examples
set QT_INSTALL_DOCS=D:\Qt\Qt5.2RC1\doc
set QT_INSTALL_EXAMPLES=D:\Qt\Qt5.2RC1\examples
set QT_INSTALL_HEADERS=D:\Qt\Qt5.2RC1\include
set QT_INSTALL_IMPORTS=D:\Qt\Qt5.2RC1\imports
set QT_INSTALL_LIBEXECS=D:\Qt\Qt5.2RC1\bin
set QT_INSTALL_LIBS=D:\Qt\Qt5.2RC1\lib
set QT_INSTALL_PLUGINS=D:\Qt\Qt5.2RC1\plugins
set QT_INSTALL_PREFIX=D:\Qt\Qt5.2RC1
set QT_INSTALL_QML=D:\Qt\Qt5.2RC1\qml
set QT_INSTALL_TESTS=D:\Qt\Qt5.2RC1\tests
set QT_INSTALL_TRANSLATIONS=D:\Qt\Qt5.2RC1\translations
set QT_VERSION=5.2.0


set CL=/D_USING_V120_SDK71_;%CL%

set LINK=/SUBSYSTEM:CONSOLE,5.01 %LINK%

